server:
  applicationConnectors:
    - type: http
      port: 9009
  adminConnectors:
    - type: http
      port: 10009
  requestLog:
    # type: classic
    timeZone: UTC
    appenders:
      - type: console
      - type: file
        # same as logging.appenders.currentLogFilename
        currentLogFilename: ./logs/dropwizard-hello-world.log
        archive: true
        archivedLogFilenamePattern: ./logs/dropwizard-hello-world-%d.log.gz
        archivedFileCount: 5
        timeZone: UTC


database:
  driverClass: org.h2.Driver
  user: sa
  password:
  url: jdbc:h2:mem:DEMO_DB;INIT=CREATE SCHEMA IF NOT EXISTS DEMO;MODE=Oracle;MV_STORE=FALSE;MVCC=FALSE;
  properties:
    charSet: UTF-8
  maxWaitForConnection: 1s
  validationQuery: "/* MyService Health Check */ SELECT 1"
  minSize: 8
  maxSize: 32
  checkConnectionWhileIdle: false
  evictionInterval: 10s
  minIdleTime: 1 minute




#
## Logging settings
#
logging:

  # The default level of all loggers. Can be OFF, ERROR, WARN, INFO, DEBUG, TRACE, or ALL.
  level: INFO
  loggers:
    "org.springframework.web": DEBUG
    "org.springframework.security": DEBUG

  appenders:
    - type: console
      threshold: DEBUG
      target: stderr

    - type: file
      threshold: DEBUG
      logFormat: "%-6level [%d{ISO8601}] [%t] %logger{5} - %X{code} %msg %n"
      currentLogFilename: ./logs/dropwizard-hello-world.log
      archivedLogFilenamePattern: ./logs/dropwizard-hello-world-%d.log.gz
      archive: true
      archivedFileCount: 5
